#pragma once
#include "shaderlib/cshader.h"
class sdk_eyeglint_ps20b_Static_Index
{
public:
	sdk_eyeglint_ps20b_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_sdk_eyeglint_ps20b 1


class sdk_eyeglint_ps20b_Dynamic_Index
{
public:
	sdk_eyeglint_ps20b_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_sdk_eyeglint_ps20b 1

